site_name: SARA-Ind -  Indicators
theme:
  name: material
  language: en

repo_url: https://github.com/urbanoeliecer/Sara-Ind

extra_css: 
  - styles/extra.css

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid 
nav:
  - Index: index.md
  - Description : description.md
  - Architecture : architecture.md
  - General Int.: indInterGnrl.md
  - Elementos Ind.: indElem.md
  - Interventions Ind.: indInterv.md
  - Definition:
    - BD structure: tecnico/bdest.md
    - Code: tecnico/entorno.md
    - Installation Guide: tecnico/installGuide.md 
    - Profiles: tecnico/roles.md
