site_name: SARA-Ind -  Indicators
theme:
  name: material
  language: en

repo_url: https://github.com/urbanoeliecer/Sara-Ind 

extra_css: 
  - styles/extra.css

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid 
nav:
  - Index: index.md
  - Principal Panel : principal.md
  - Ind. General: indInterGnrl.md
  - Ind. de Infraestructura: indElem.md
  - Ind. de Interventions: indInterv.md
  - Styles: back/estilos.md
  - Definition:
    - Conection: back/conexion.md
    - BD structure: tecnico/bdest.md
    - Code: tecnico/entorno.md
    - Profiles: tecnico/roles.md
    - Requeriments: tecnico/req.md
